### ISSUE TITLE
Weird section on README.md

### ISSUE THREAD

**Issue by mperezv** [coopdevs/coopdevs-old-web#117]
There is this "Prueba" section on the `README` that seems a forgotten thing. Should I remove it? 

https://github.com/coopdevs/coopdevs.github.io/blob/develop/README.md#prueba

**Comment by enricostano** [comment]
https://github.com/coopdevs/coopdevs.github.io/commit/1bf21ee30d711c9221aac10caf6fae1ae62a5c40

It seems so, yep. Thanks!
