### ISSUE TITLE
Use PAM a PAM official banner

### ISSUE THREAD

**Issue by enricostano** [coopdevs/coopdevs-old-web#24]
Maybe we should use the official PAM a PAM banner, I suggest the round one:

https://pamapam.org/ca/baners-pam-pam/

Thoughts?

**Comment by sauloperez** [comment]
![screenshot from 2018-10-11 12-12-04](https://user-images.githubusercontent.com/762088/46797248-ecdf4b00-cd4e-11e8-8e9f-cc0c425b36d2.png)

Done. Can we close this?

**Comment by enricostano** [comment]
@sauloperez yep, thanks!
