### ISSUE TITLE
Automate build & deploy

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/coopdevs-old-web#36]
This stems from https://github.com/coopdevs/coopdevs.github.io/pull/31#issuecomment-446232057.

As we want to have people other than devs to write on our site, it's important to have the build and deploy happen elsewhere, not in people's machines. While we're able to setup the project on our dev machines, others don't.

Also, it's less error-prone to trust these steps to a 3rd party service/server so no conflicts with dependencies or problems with the dev machine stop you from deploying.

**Comment by sauloperez** [comment]
Gitlab pages is an option here. Apparently, they support any Jekyll plugin and the deploy uses their CI pipelines. Reference: https://www.scivision.co/gitlab-pages-vs-github-pages/

**Comment by sauloperez** [comment]
I'd do this as soon as we do a new iteration on the website's design and content. I would really glad to use my brain for other things other than having to deploy when PRs get merged. I prefer a computer to do it for me.

I worked already with Gitlab Pages at https://gitlab.com/sauloperez/municipalistes_republicans and it was a smooth experience. It works out of the box with their CI/CD templates :ok_hand:

**Comment by enricostano** [comment]
GitLab o ke ase?

**Comment by sauloperez** [comment]
Done in https://github.com/coopdevs/coopdevs.github.io/pull/70. We found a quicker solution that didn't require moving the repo.
