### ISSUE TITLE
Fix DNS record warning

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/coopdevs-old-web#50]
I get the following warning on my inbox every time I deploy:

The page build completed successfully, but returned the following warning for the `master` branch:

The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://help.github.com/en/articles/using-a-custom-domain-with-github-pages.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

**Comment by enricostano** [comment]
I already did this once a couple of months ago.... :see_no_evil:

**Comment by sauloperez** [comment]
so you can do it once again, right? :trollface:

**Comment by enricostano** [comment]
Done.
