### ISSUE TITLE
Remove "-" from homepage title

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/coopdevs-old-web#76]
We use "-" in title for subtitle, for example Blog post title would be "Coopdevs - Blog post title" in home we want to remove it.

![2019-10-03-121733_1960x2160_scrot](https://user-images.githubusercontent.com/2297137/66118981-fd2fac00-e5d7-11e9-92f8-96696348e855.png)

**Comment by agawish** [comment]
I can work on that, if it is not too much of a trouble

**Comment by agawish** [comment]
@sseerrggii I will have to merge against `master` branch.
Also do you want to remove the `-` from other pages as well, such as `404` and `blog` pages?

**Comment by sseerrggii** [comment]
Hey @agawish ! Welcome!!

We only want to remove "-" on the pages that don't have a particular subtitle

 watch out because the main branch is `develop` and not `master` , master is only used to deploy to github pages

**Comment by agawish** [comment]
Hi @sseerrggii ,
Thanks, I've created the PR against `master` branch, I was careful :) 
https://github.com/coopdevs/coopdevs.github.io/pull/79
