### ISSUE TITLE
Unhardcode footer's background color

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/coopdevs-old-web#80]
We should remove the following styling

https://github.com/coopdevs/coopdevs.github.io/blob/20a38b214ffc201f17ba7f00f79ec16dfeacfad5/_includes/footer.html#L1

to a [TailwindCSS](http://tailwindcss.com/) color in 

https://github.com/coopdevs/coopdevs.github.io/blob/20a38b214ffc201f17ba7f00f79ec16dfeacfad5/_includes/tailwind.config.js#L6

as `gray 100`. I don't see any DOM element using the existing gray 100 so we should be able to replace it.

**Comment by estim** [comment]
I'll take it. Has never dealt with Tailwind but will try my best!

**Comment by sauloperez** [comment]
Thanks @estim ! and welcome to Coopdevs! I felt in love with Tailwind CSS recently!

**Comment by sauloperez** [comment]
Closed by https://github.com/coopdevs/coopdevs.github.io/pull/83
