### ISSUE TITLE
Use default.new layout in the 404 page

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/coopdevs-old-web#81]
We need to use the [default.new](https://github.com/coopdevs/coopdevs.github.io/blob/develop/_layouts/default.new.html) layout for the 404.html page. 

The trick here is that it looks like this if we only replace the Jekyll `layout` variable

![Screenshot from 2019-10-03 17-08-47](https://user-images.githubusercontent.com/762088/66139424-b3a78700-e600-11e9-8f57-5e7a6ebf9d79.png)

**Comment by ankush-0x90** [comment]
Hi @sauloperez I would like to take this as my first issue for hacktoberfest. Looking forward to give what I have got to be awesome contributor in future..

**Comment by ankush-0x90** [comment]
Hi @sauloperez do we need footer in 404? means I don't think we need but can you suggest me filtering footer content out of default.new when included in 404

**Comment by sauloperez** [comment]
Hi @asprazz and thanks for your offering! yes, I think having a footer it'll make the page look consistent with the rest of the site. I don't how difficult it'll be so we should at least show the navbar.
