### ISSUE TITLE
Cache dependencies in CircleCI

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/coopdevs-old-web#82]
It'd be great to speed up CI runs with dependency caching. Circle CI has documentation about it in https://circleci.com/docs/2.0/caching/#full-example-of-saving-and-restoring-cache,  https://circleci.com/docs/2.0/language-ruby/ and https://circleci.com/docs/2.0/language-javascript/.

I'm pretty sure we can even find examples of static sites running on Circle CI and see how they deal with this.

Note we install dependencies with both bundler and yarn.

**Comment by cjwilburn** [comment]
I think I may be able to take this.

**Comment by sauloperez** [comment]
Hi and welcome @cjwilburn ! It's all yours. Don't hesitate to ask us anything.

**Comment by cjwilburn** [comment]
Thanks!

**Comment by cjwilburn** [comment]
Hello! I've submitted #101 to address this issue. Thanks!

**Comment by sauloperez** [comment]
Closed by https://github.com/coopdevs/coopdevs.github.io/pull/101
